#!/usr/bin/env node
// Real-browser smoke test for the app shell (M1 brief verification step,
// extended at M2). Assumes the engine (uvicorn) and `npm run dev` (Vite,
// port 1420) are already running -- this script only drives Chromium
// against them.
//
// Flow: load the app -> create a project -> fill T-01 (Project Picker) to
// a full-DMAIC route -> save -> see the version badge -> open T-03
// (Charter) -> type a solution-shaped problem statement -> save -> assert
// the solution-language prescore flag renders, both in the prescore strip
// and as a field-level flag -> T-02/T-04/T-05 + a gate override -> M2:
// import the coffee-bar wait-times fixture via T-11, confirm the quality
// scan renders, save it -> run T-13 Baseline against it and assert the
// stability verdict + sigma-convention-label render -> open T-14 and
// assert a Pareto verdict headline renders. Fails on any uncaught page error.
//
// Usage: node tools/smoke-browser.mjs
// Env:   APP_URL (default http://localhost:1420)

import { chromium } from "playwright";
import path from "node:path";
import { fileURLToPath } from "node:url";

const APP_URL = process.env.APP_URL || "http://localhost:1420";
const CHROMIUM_PATH = process.env.PW_CHROMIUM_PATH || "/opt/pw-browsers/chromium";
const TIMEOUT_MS = 20_000;

const SCRIPT_DIR = path.dirname(fileURLToPath(import.meta.url));
const FIXTURE_CSV_PATH = path.join(SCRIPT_DIR, "fixtures", "coffee-bar-wait-times.csv");
const FIXTURE_LABEL = "coffee-bar-wait-times.csv (24 rows)"; // must match source_filename + row_count exactly
const FIXTURE_PNG_PATH = path.join(SCRIPT_DIR, "fixtures", "floorplan-fixture.png"); // 700x550, generated by a stdlib-only Python script (see build report)

const steps = [];
const pageErrors = [];
const consoleErrors = [];

function log(status, name, detail) {
  const line = `[${status}] ${name}${detail ? " -- " + detail : ""}`;
  console.log(line);
  steps.push({ status, name, detail });
}

async function step(name, fn) {
  try {
    await fn();
    log("PASS", name);
  } catch (err) {
    log("FAIL", name, err instanceof Error ? err.message : String(err));
    throw err;
  }
}

function assert(condition, message) {
  if (!condition) throw new Error(message);
}

// Strips everything but digits/./- so "6,000" or "Total: 9,600" reads as a
// plain number, regardless of the browser's thousands-separator locale.
function numeric(text) {
  if (text == null) return NaN;
  return Number(text.replace(/[^\d.-]/g, ""));
}

const CRITERIA_KEYS = [
  "scope_narrow",
  "measurable_outcome",
  "data_obtainable",
  "process_owner_engaged",
  "business_impact_plausible",
];

async function main() {
  const browser = await chromium.launch({
    executablePath: CHROMIUM_PATH,
    args: ["--no-sandbox"],
  });
  const page = await browser.newPage();
  page.setDefaultTimeout(TIMEOUT_MS);

  page.on("pageerror", (err) => {
    pageErrors.push(err.message);
    console.error(`[PAGE ERROR] ${err.message}`);
  });
  page.on("console", (msg) => {
    if (msg.type() === "error") {
      consoleErrors.push(msg.text());
      console.error(`[CONSOLE ERROR] ${msg.text()}`);
    }
  });

  const runId = Date.now();
  const projectName = `Smoke Test Coffee Bar ${runId}`;

  try {
    await step("load app", async () => {
      await page.goto(APP_URL, { waitUntil: "domcontentloaded" });
      await page.locator('[data-testid="create-project-name"]').waitFor();
    });

    await step("create project", async () => {
      await page.locator('[data-testid="create-project-name"]').fill(projectName);
      await page.locator('[data-testid="create-project-submit"]').click();
      await page.locator('[data-testid="topbar-project-name"]').waitFor();
      const shown = await page.locator('[data-testid="topbar-project-name"]').textContent();
      assert(shown?.trim() === projectName, `top bar shows ${JSON.stringify(shown)}, expected ${JSON.stringify(projectName)}`);
    });

    await step("open T-01 Project Picker", async () => {
      await page.locator('[data-testid="nav-tool-T-01"]').click();
      await page.locator('[data-testid="picker-save"]').waitFor();
    });

    await step("fill T-01 to a full-DMAIC route", async () => {
      for (const key of CRITERIA_KEYS) {
        await page.locator(`[data-testid="picker-${key}-yes"]`).click();
        await page.locator(`[data-testid="picker-${key}-detail"]`).fill(`Smoke-test evidence for ${key}.`);
      }
      await page.locator('[data-testid="picker-route-full-DMAIC"]').click();
      const saveBtn = page.locator('[data-testid="picker-save"]');
      assert(await saveBtn.isEnabled(), "Save button should be enabled once all criteria + route are set");
    });

    await step("save T-01 and see the version badge", async () => {
      await page.locator('[data-testid="picker-save"]').click();
      await page.locator('[data-testid="picker-version-badge"]').waitFor();
      const badge = await page.locator('[data-testid="picker-version-badge"]').textContent();
      assert(badge?.includes("v1"), `expected version badge to show v1, got ${JSON.stringify(badge)}`);
    });

    await step("open T-03 Project Charter", async () => {
      await page.locator('[data-testid="nav-tool-T-03"]').click();
      await page.locator('[data-testid="charter-save"]').waitFor();
    });

    await step("fill T-03 with a solution-shaped problem statement", async () => {
      // Solution-shaped on purpose (contains "train" -- prescore/charter.py's
      // SOLUTION_LANGUAGE_KEYWORDS) so the flag this test is checking for
      // actually has something to catch.
      await page.locator('[data-testid="charter-problem-what"]').fill("Train the operators on the new molding process");
      await page.locator('[data-testid="charter-problem-where"]').fill("Line 2, Plant A");
      await page.locator('[data-testid="charter-problem-when"]').fill("Q2 2026");
      await page.locator('[data-testid="charter-magnitude-number"]').fill("6.2");
      await page.locator('[data-testid="charter-magnitude-unit"]').fill("%");
      await page.locator('[data-testid="charter-magnitude-period"]').fill("Q2 2026");

      await page.locator('[data-testid="charter-goal-statement"]').fill("Reduce line-2 scrap from 6.2% to 3% by Nov 30, 2026.");
      await page.locator('[data-testid="charter-goal-metric-name"]').fill("line-2 scrap rate");
      await page.locator('[data-testid="charter-goal-target"]').fill("3");
      await page.locator('[data-testid="charter-goal-unit"]').fill("%");
      await page.locator('[data-testid="charter-goal-target-date"]').fill("2026-11-30");

      await page.locator('[data-testid="charter-scope-in"]').fill("Line 2 molding station only");
      await page.locator('[data-testid="charter-scope-out"]').fill("Lines 1 and 3, packaging");

      await page.locator('[data-testid="charter-owner-name"]').fill("Maria Ortiz");
      await page.locator('[data-testid="charter-owner-role"]').fill("Line-2 supervisor");

      await page.locator('[data-testid="charter-team-0-name"]').fill("Maria Ortiz");
      await page.locator('[data-testid="charter-team-0-role"]').fill("Line-2 supervisor");

      await page.locator('[data-testid="charter-timeline-0-name"]').fill("Define complete");
      await page.locator('[data-testid="charter-timeline-0-date"]').fill("2026-08-21");

      await page.locator('[data-testid="charter-impact-amount"]').fill("40000");
      await page.locator('[data-testid="charter-impact-unit"]').fill("dollars");
      await page.locator('[data-testid="charter-impact-basis"]').fill("Q2 actuals x 4");

      assert(await page.locator('[data-testid="charter-save"]').isEnabled(), "Save button should be enabled once required fields are filled");
    });

    await step("save T-03 and see the version badge", async () => {
      await page.locator('[data-testid="charter-save"]').click();
      await page.locator('[data-testid="charter-version-badge"]').waitFor();
      const badge = await page.locator('[data-testid="charter-version-badge"]').textContent();
      assert(badge?.includes("v1"), `expected version badge to show v1, got ${JSON.stringify(badge)}`);
    });

    await step("assert the Export PDF button is enabled now that a version is saved", async () => {
      // Button-state only -- actually triggering the download goes through
      // a Tauri save dialog in the packaged app, which isn't reachable
      // from a plain Chromium/Playwright session (M1 export brief).
      const exportBtn = page.locator('[data-testid="charter-export-pdf"]');
      await exportBtn.waitFor();
      assert(await exportBtn.isEnabled(), "Export PDF button should be enabled once a charter version is saved");
    });

    await step("assert the solution-language flag renders in the prescore strip", async () => {
      const pill = page.locator('[data-testid="prescore-check-problem_statement_solution_language"]');
      await pill.waitFor();
      const status = await pill.getAttribute("data-status");
      assert(status === "flag", `expected prescore check status "flag", got ${JSON.stringify(status)}`);
      const text = await pill.textContent();
      assert(
        text?.toLowerCase().includes("solution language"),
        `expected the pill's label to mention solution language, got ${JSON.stringify(text)}`,
      );
    });

    await step("assert the solution-language flag renders on the field itself", async () => {
      // ProblemStatementSection's "What" field is flagged via
      // CharterForm's fieldFlag() mapping (charterChecks.ts), independent
      // of the prescore strip -- render the same information twice for
      // two different jobs (strip = overview, field = where to fix it).
      // The flag message div is a sibling of the input inside .sigma-field
      // (see design/components/Field.tsx), so one level up is enough.
      const whatField = page.locator('[data-testid="charter-problem-what"]').locator("..");
      await whatField.locator(".sigma-field__flag-message").waitFor();
      const flagText = await whatField.locator(".sigma-field__flag-message").textContent();
      assert(
        flagText?.toLowerCase().includes("solution") || flagText?.toLowerCase().includes("cause"),
        `expected the field-level flag to mention solution/cause language, got ${JSON.stringify(flagText)}`,
      );
    });

    // ---- Define-completion additions (M1 build-out): T-02/T-04/T-05 real
    // forms, plus the gate override feedback loop (gates.py's
    // _covering_override). The override is exercised BEFORE T-05 is saved
    // on purpose: define_to_measure requires T-03+T-04+T-05, and by the
    // time all three exist the gate is plain CLEAR with nothing left to
    // override -- checking it here, with T-05 still missing, is the only
    // point in this flow with a real soft block to clear. ----

    await step("open T-02 COPQ and fill two cost rows", async () => {
      await page.locator('[data-testid="nav-tool-T-02"]').click();
      await page.locator('[data-testid="copq-save"]').waitFor();

      await page.locator('[data-testid="copq-row-0-quantity"]').fill("500");
      await page.locator('[data-testid="copq-row-0-rate"]').fill("12");
      await page.locator('[data-testid="copq-row-0-period"]').fill("Q2 2026");
      await page.locator('[data-testid="copq-row-0-basis"]').fill("Q2 scrap log export");

      await page.getByRole("button", { name: "+ Add cost row" }).click();
      await page.locator('[data-testid="copq-row-1-category"]').selectOption("rework");
      await page.locator('[data-testid="copq-row-1-quantity"]').fill("80");
      await page.locator('[data-testid="copq-row-1-rate"]').fill("45");
      await page.locator('[data-testid="copq-row-1-period"]').fill("Q2 2026");
      await page.locator('[data-testid="copq-row-1-basis"]').fill("labor hours x loaded rate");

      assert(await page.locator('[data-testid="copq-save"]').isEnabled(), "COPQ save button should be enabled once both rows are filled");
    });

    await step("save T-02 and see the server-computed total render", async () => {
      await page.locator('[data-testid="copq-save"]').click();
      await page.locator('[data-testid="copq-version-badge"]').waitFor();
      // The version badge renders as soon as the save POST resolves, but
      // useCopqForm's reload-after-save GET (what actually populates the
      // engine-computed amounts/total) is a separate awaited step just
      // after -- wait for that render to land before reading values.
      await page.waitForFunction(() => document.querySelector('[data-testid="copq-row-0-amount"]')?.value !== "not yet computed");

      const row0Amount = await page.locator('[data-testid="copq-row-0-amount"]').inputValue();
      const row1Amount = await page.locator('[data-testid="copq-row-1-amount"]').inputValue();
      assert(numeric(row0Amount) === 6000, `expected row 0's engine-computed amount to be 6000 (500 x 12), got ${JSON.stringify(row0Amount)}`);
      assert(numeric(row1Amount) === 3600, `expected row 1's engine-computed amount to be 3600 (80 x 45), got ${JSON.stringify(row1Amount)}`);

      const totalHeadline = await page.locator('[data-testid="copq-total"] .sigma-verdict__headline').textContent();
      assert(numeric(totalHeadline) === 9600, `expected the server-computed total to read 9600 (6000 + 3600), got ${JSON.stringify(totalHeadline)}`);
      const totalDetail = await page.locator('[data-testid="copq-total"] .sigma-verdict__detail').textContent();
      assert(
        totalDetail?.toLowerCase().includes("computed by the engine"),
        `expected the total panel to say it's engine-computed, got ${JSON.stringify(totalDetail)}`,
      );
    });

    await step("open T-04 SIPOC and fill five clean process steps", async () => {
      await page.locator('[data-testid="nav-tool-T-04"]').click();
      await page.locator('[data-testid="sipoc-save"]').waitFor();

      await page.locator('[data-testid="sipoc-supplier-0"]').fill("Resin vendor");
      await page.locator('[data-testid="sipoc-input-0"]').fill("Raw resin pellets");

      const stepNames = ["Receive order", "Prep", "Mold", "Inspect", "Package"];
      await page.locator('[data-testid="sipoc-step-0"]').fill(stepNames[0]);
      for (let i = 1; i < stepNames.length; i++) {
        await page.getByRole("button", { name: "+ Add step" }).click();
        await page.locator(`[data-testid="sipoc-step-${i}"]`).fill(stepNames[i]);
      }

      await page.locator('[data-testid="sipoc-scope-start"]').fill("Order received");
      await page.locator('[data-testid="sipoc-scope-end"]').fill("Order handed off");

      await page.locator('[data-testid="sipoc-output-0"]').fill("Molded part");
      await page.locator('[data-testid="sipoc-customer-0"]').fill("Assembly line");

      assert(await page.locator('[data-testid="sipoc-save"]').isEnabled(), "SIPOC save button should be enabled once all five columns are filled");
    });

    await step("save T-04 and assert the step-count prescore reads clean", async () => {
      await page.locator('[data-testid="sipoc-save"]').click();
      await page.locator('[data-testid="sipoc-version-badge"]').waitFor();

      const pill = page.locator('[data-testid="prescore-check-step_count_range"]');
      await pill.waitFor();
      const status = await pill.getAttribute("data-status");
      assert(status === "pass", `expected 5 steps to read a clean (pass) step-count range, got ${JSON.stringify(status)}`);
    });

    await step("switch to Measure and confirm the Define exit gate soft-blocks (T-05 still missing)", async () => {
      await page.locator('[data-testid="nav-tool-T-06"]').click();
      await page.locator('[data-testid="gate-override-open"]').waitFor();
    });

    await step("log a soft-block override with a reason and confirm the gate renders cleared-with-note", async () => {
      const overrideReason = "Charter, COPQ, and SIPOC are done; unblocking Measure prep while VoC/CTQ is finished.";
      await page.locator('[data-testid="gate-override-open"]').click();
      await page.locator('[data-testid="gate-override-reason"]').fill(overrideReason);
      await page.locator('[data-testid="gate-override-submit"]').click();

      const clearedNote = page.locator(".sigma-verdict", { hasText: "cleared, override logged" });
      await clearedNote.waitFor();
      const bannerText = await clearedNote.textContent();
      assert(
        bannerText?.includes(overrideReason),
        `expected the cleared-with-note banner to include the logged override reason, got ${JSON.stringify(bannerText)}`,
      );
    });

    await step("open T-05 VoC -> CTQ and build one statement -> need -> CTQ", async () => {
      await page.locator('[data-testid="nav-tool-T-05"]').click();
      await page.locator('[data-testid="voc-ctq-save"]').waitFor();

      await page.locator('[data-testid="voc-customer-0-role"]').fill("external - end buyer");

      await page.locator('[data-testid="voc-statement-0-role"]').fill("external - end buyer");
      await page.locator('[data-testid="voc-statement-0-text"]').fill("Parts sometimes arrive cracked.");
      await page.locator('[data-testid="voc-statement-0-detail"]').fill("2026 Q2 complaint log");

      await page.locator('[data-testid="voc-need-0-text"]').fill("Parts must arrive intact");
      await page.locator('[data-testid="voc-need-0-statement-S1"]').check();

      await page.locator('[data-testid="voc-ctq-0-need"]').selectOption("N1");
      await page.locator('[data-testid="voc-ctq-0-measure"]').fill("crack rate at receiving");
      await page.locator('[data-testid="voc-ctq-0-target"]').fill("<1%");
      await page
        .locator('[data-testid="voc-ctq-0-critical-check"]')
        .fill("Customer-critical: cracked parts are returned and re-ordered; not chosen for ease of measurement.");

      await page.locator('[data-testid="voc-primary-ctq"]').selectOption("C1");
      await page.locator('[data-testid="voc-charter-link"]').fill("matches charter primary metric: line-2 scrap rate");

      assert(await page.locator('[data-testid="voc-ctq-save"]').isEnabled(), "VoC/CTQ save button should be enabled once the tree is complete");
    });

    await step("save T-05 and assert tree-completeness prescore passes", async () => {
      await page.locator('[data-testid="voc-ctq-save"]').click();
      await page.locator('[data-testid="voc-ctq-version-badge"]').waitFor();

      const pill = page.locator('[data-testid="prescore-check-tree_completeness"]');
      await pill.waitFor();
      const status = await pill.getAttribute("data-status");
      assert(status === "pass", `expected the VoC/CTQ tree to read complete (pass), got ${JSON.stringify(status)}`);
    });

    // ---- M2 additions: T-11 dataset import, T-13 baseline, T-14 charts.
    // define_to_measure is already CLEAR by this point (T-03/T-04/T-05 all
    // saved above), so no further gate handling is needed here. ----

    await step("open T-11 Data Collection Plan and import the coffee-bar fixture", async () => {
      await page.locator('[data-testid="nav-tool-T-11"]').click();
      await page.locator('[data-testid="dataimport-file-input"]').setInputFiles(FIXTURE_CSV_PATH);
      await page.locator('[data-testid="dataimport-column-preview"]').waitFor();
      await page.locator('[data-testid="dataimport-quality-scan"]').waitFor();
    });

    await step("confirm the import quality scan renders", async () => {
      const scanText = await page.locator('[data-testid="dataimport-quality-scan"]').textContent();
      assert(
        scanText?.includes("24 total rows scanned"),
        `expected the quality scan to plainly report the fixture's 24 rows, got ${JSON.stringify(scanText)}`,
      );
    });

    await step("save the imported dataset", async () => {
      await page.locator('[data-testid="dataimport-save"]').click();
      await page.locator('[data-testid="dataimport-save-confirmation"]').waitFor();
      const confirmText = await page.locator('[data-testid="dataimport-save-confirmation"]').textContent();
      assert(confirmText?.includes("24 rows"), `expected the save confirmation to mention 24 rows, got ${JSON.stringify(confirmText)}`);
    });

    await step("open T-13 Baseline and pick the imported dataset + wait_seconds column", async () => {
      await page.locator('[data-testid="nav-tool-T-13"]').click();
      await page.locator('[data-testid="baseline-dataset-select"]').waitFor();
      await page.locator('[data-testid="baseline-dataset-select"]').selectOption({ label: FIXTURE_LABEL });
      await page.locator('[data-testid="baseline-column-select"]').selectOption("wait_seconds");
    });

    await step("enter spec limits and confirm the operational definition", async () => {
      await page.locator('[data-testid="baseline-usl-input"]').fill("105");
      await page.locator('[data-testid="baseline-lsl-input"]').fill("85");
      await page.locator('[data-testid="baseline-op-def-checkbox"]').check();
      assert(
        await page.locator('[data-testid="baseline-run"]').isEnabled(),
        "Run baseline button should be enabled once data + specs + operational definition are set",
      );
    });

    await step("run the baseline and assert the stability verdict + sigma-convention label render", async () => {
      await page.locator('[data-testid="baseline-run"]').click();
      await page.locator('[data-testid="baseline-stability-verdict"]').waitFor();

      const stabilityHeadline = await page.locator('[data-testid="baseline-stability-verdict"] .sigma-verdict__headline').textContent();
      assert(
        stabilityHeadline?.includes("stable: 24 points"),
        `expected the I-MR chart's verdict headline to carry the engine's stable-24-points note, got ${JSON.stringify(stabilityHeadline)}`,
      );

      await page.locator('[data-testid="baseline-sigma-level"]').waitFor();
      const sigmaHeadline = await page.locator('[data-testid="baseline-sigma-level"] .sigma-verdict__headline').textContent();
      assert(
        sigmaHeadline?.includes("with 1.5σ shift"),
        `expected the sigma level headline to carry the shift-convention label, got ${JSON.stringify(sigmaHeadline)}`,
      );
    });

    await step("open T-14 and assert a Pareto verdict headline renders", async () => {
      await page.locator('[data-testid="nav-tool-T-14"]').click();
      await page.locator('[data-testid="chartset-dataset-select"]').waitFor();
      await page.locator('[data-testid="chartset-dataset-select"]').selectOption({ label: FIXTURE_LABEL });
      await page.locator('[data-testid="chartset-pareto-column"]').waitFor();
      await page.locator('[data-testid="chartset-pareto-column"]').selectOption("delay_cause");

      const paretoHeadline = page.locator('[data-testid="chartset-pareto"] .sigma-verdict__headline');
      await paretoHeadline.waitFor();
      const text = await paretoHeadline.textContent();
      assert(
        text?.toLowerCase().includes("vital few") && text?.includes("register"),
        `expected the Pareto verdict headline to name the vital few including "register", got ${JSON.stringify(text)}`,
      );
    });
    // ---- M2 addition: T-06 Process Map (swimlane) + Waste Walk -- the
    // Konva canvas tool. Konva nodes are canvas-drawn (no DOM test ids), so
    // this drives the map through the inspector panel + add-lane/add-step
    // buttons rather than pixel drags -- lanes/steps are real Konva-
    // rendered cards on screen, just built via the reliable HTML control
    // surface next to the canvas. ----

    await step("open T-06 and build 2 lanes", async () => {
      await page.locator('[data-testid="nav-tool-T-06"]').click();
      await page.locator('[data-testid="processmap-save"]').waitFor();
      await page.locator('[data-testid="processmap-add-lane"]').click();
      await page.locator('[data-testid="processmap-add-lane"]').click();
      await page.locator('[data-testid="processmap-lane-0-name"]').fill("Customer");
      await page.locator('[data-testid="processmap-lane-0-owner"]').fill("Front counter lead");
      await page.locator('[data-testid="processmap-lane-1-name"]').fill("Barista");
      await page.locator('[data-testid="processmap-lane-1-owner"]').fill("Shift lead");
    });

    await step("add 4 steps across the 2 lanes (2 per lane), assert they render", async () => {
      await page.locator('[data-testid="processmap-add-step-0"]').click();
      await page.locator('[data-testid="processmap-step-name"]').fill("Place order");
      await page.locator('[data-testid="processmap-step-reason"]').fill("Customer directly asks for what they want.");
      await page.locator('[data-testid="processmap-step-time"]').fill("2");

      await page.locator('[data-testid="processmap-add-step-1"]').click();
      await page.locator('[data-testid="processmap-step-name"]').fill("Wait for register");
      await page.locator('[data-testid="processmap-step-type"]').selectOption("non_value_add");
      await page.locator('[data-testid="processmap-step-reason"]').fill("Customer gets nothing while waiting.");
      await page.locator('[data-testid="processmap-step-time"]').fill("9");

      await page.locator('[data-testid="processmap-add-step-0"]').click();
      await page.locator('[data-testid="processmap-step-name"]').fill("Make drink");
      await page.locator('[data-testid="processmap-step-reason"]').fill("Directly produces what the customer is paying for.");
      await page.locator('[data-testid="processmap-step-time"]').fill("3");

      await page.locator('[data-testid="processmap-add-step-1"]').click();
      await page.locator('[data-testid="processmap-step-name"]').fill("Hand off");
      await page.locator('[data-testid="processmap-step-type"]').selectOption("enabling");
      await page.locator('[data-testid="processmap-step-time"]').fill("1");

      const rows = page.locator('[data-testid^="processmap-step-row-"]');
      await rows.first().waitFor();
      assert((await rows.count()) === 4, `expected 4 step rows to render, got ${await rows.count()}`);
      await page.locator('[data-testid="processmap-canvas"] canvas').first().waitFor();
    });

    await step("confirm the NVA tag + reason and the checked waste + note took hold", async () => {
      // "Hand off" is still the selected step from the block above; re-open
      // "Wait for register" via its StepsList row (label text is stable,
      // its generated step_id is not) to read back what was typed on it.
      await page.locator('[data-testid^="processmap-step-row-"]', { hasText: "Wait for register" }).click();
      assert(
        (await page.locator('[data-testid="processmap-step-type"]').inputValue()) === "non_value_add",
        "expected the Wait for register step to still read non_value_add",
      );
      const reason = await page.locator('[data-testid="processmap-step-reason"]').inputValue();
      assert(reason.length > 0, "expected the NVA step to carry a non-empty reason");

      await page.locator('[data-testid="processmap-waste-waiting"]').check();
      await page.locator('[data-testid="processmap-waste-note-waiting"]').fill("Line backs up during the morning rush.");
      assert(await page.locator('[data-testid="processmap-waste-waiting"]').isChecked(), "expected the waiting waste checkbox to be checked");
    });

    await step("connect two steps", async () => {
      await page.locator('[data-testid="processmap-connector-from"]').selectOption({ label: "Place order" });
      await page.locator('[data-testid="processmap-connector-to"]').selectOption({ label: "Wait for register" });
      await page.locator('[data-testid="processmap-connector-add"]').click();
      const list = page.locator(".sigma-processmap-connector-list", { hasText: "Place order" });
      await list.waitFor();
      const text = await list.textContent();
      assert(text?.includes("Wait for register"), `expected the connector list to show Place order -> Wait for register, got ${JSON.stringify(text)}`);
    });

    await step("enter demand fields and save", async () => {
      // available=240, demand=48 -> pace=5.00 min/unit; the 9-minute "Wait
      // for register" step is the hand-checkable bottleneck and exceeds it.
      await page.locator('[data-testid="processmap-demand-time"]').fill("240");
      await page.locator('[data-testid="processmap-demand-units"]').fill("48");
      await page.locator('[data-testid="processmap-save"]').click();
      await page.locator('[data-testid="processmap-version-badge"]').waitFor();
      const badge = await page.locator('[data-testid="processmap-version-badge"]').textContent();
      assert(badge?.includes("v1"), `expected version badge to show v1, got ${JSON.stringify(badge)}`);
    });

    await step("assert the engine's bottleneck banner names the right step from the fixture times", async () => {
      const headline = page.locator('[data-testid="processmap-bottleneck-banner"] .sigma-verdict__headline');
      await headline.waitFor();
      const text = await headline.textContent();
      assert(
        text?.includes("Wait for register") && text?.includes("9") && text?.includes("5.00"),
        `expected the bottleneck banner to name "Wait for register" at 9 min vs a 5.00 pace, got ${JSON.stringify(text)}`,
      );
    });

    // ---- M2 addition: T-07 Spaghetti Diagram -- the interactive
    // flagship. Calibration and tracing are inherently "click a precise
    // canvas point" interactions (unlike T-06's connectors, there is no
    // faithful non-canvas proxy control), so this drives the Konva
    // <canvas> directly via Playwright's position-relative clicks, same
    // coordinate system the app itself stores (SpaghettiCanvas.tsx's
    // getRelativePointerPosition, untransformed at scale=1/position=0
    // since neither pan nor zoom is exercised here). ----

    await step("open T-07 and upload the floor-plan fixture", async () => {
      await page.locator('[data-testid="nav-tool-T-07"]').click();
      await page.locator('[data-testid="spaghetti-save"]').waitFor();
      await page.locator('[data-testid="spaghetti-floorplan-input"]').setInputFiles(FIXTURE_PNG_PATH);
      await page.locator('[data-testid="spaghetti-floorplan-loaded"]').waitFor();
    });

    const spaghettiCanvas = page.locator('[data-testid="spaghetti-canvas"] canvas').first();

    await step("calibrate: draw a 100px line and confirm it as 10 meters", async () => {
      await page.locator('[data-testid="spaghetti-mode-calibrate"]').click();
      await spaghettiCanvas.click({ position: { x: 50, y: 50 } });
      await spaghettiCanvas.click({ position: { x: 150, y: 50 } });
      await page.locator('[data-testid="spaghetti-calibration-length"]').fill("10");
      await page.locator('[data-testid="spaghetti-calibration-unit"]').selectOption("meters");
      await page.locator('[data-testid="spaghetti-calibration-confirm"]').click();

      const badge = await page.locator('[data-testid="spaghetti-calibration-badge"]').textContent();
      assert(badge?.includes("10") && badge?.includes("meters"), `expected the calibration badge to show 10 meters, got ${JSON.stringify(badge)}`);
    });

    await step("add an operator", async () => {
      await page.locator('[data-testid="spaghetti-add-operator"]').click();
      await page.locator('[data-testid="spaghetti-operator-0-name"]').fill("Barista");
    });

    await step("trace a current route: two segments, 300px + 400px (hand-computable 70m at 10px/m)", async () => {
      await page.locator('[data-testid="spaghetti-trace-operator"]').selectOption({ label: "Barista" });
      await page.locator('[data-testid="spaghetti-trace-trip-label"]').fill("Register to grinder");
      await page.locator('[data-testid="spaghetti-trace-frequency"]').fill("6");
      await page.locator('[data-testid="spaghetti-trace-start"]').click();

      await spaghettiCanvas.click({ position: { x: 50, y: 100 } });
      await spaghettiCanvas.click({ position: { x: 350, y: 100 } }); // +300px
      await spaghettiCanvas.click({ position: { x: 350, y: 500 } }); // +400px
      await page.locator('[data-testid="spaghetti-trace-finish"]').click();

      await page.locator('[data-testid="spaghetti-route-0"]').waitFor();
    });

    await step("save T-07 and assert the engine's route metrics render exactly (70 m/trip, 420 m/day)", async () => {
      await page.locator('[data-testid="spaghetti-save"]').click();
      await page.locator('[data-testid="spaghetti-version-badge"]').waitFor();

      await page.locator('[data-testid="spaghetti-route-0-distance"]').waitFor();
      const distanceText = await page.locator('[data-testid="spaghetti-route-0-distance"]').textContent();
      assert(numeric(distanceText) === 70, `expected route 0's distance to read 70 m/trip, got ${JSON.stringify(distanceText)}`);

      const dailyText = await page.locator('[data-testid="spaghetti-route-0-daily-distance"]').textContent();
      assert(numeric(dailyText) === 420, `expected route 0's daily distance to read 420 m/day, got ${JSON.stringify(dailyText)}`);
    });

    await step("switch to proposed and trace a 350px route (hand-computable 35m)", async () => {
      await page.locator('[data-testid="spaghetti-layout-mode-proposed"]').click();
      await page.locator('[data-testid="spaghetti-trace-operator"]').selectOption({ label: "Barista" });
      await page.locator('[data-testid="spaghetti-trace-trip-label"]').fill("Register to grinder (proposed)");
      await page.locator('[data-testid="spaghetti-trace-frequency"]').fill("6");
      await page.locator('[data-testid="spaghetti-trace-start"]').click();

      await spaghettiCanvas.click({ position: { x: 50, y: 100 } });
      await spaghettiCanvas.click({ position: { x: 400, y: 100 } }); // +350px, single segment
      await page.locator('[data-testid="spaghetti-trace-finish"]').click();
      await page.locator('[data-testid="spaghetti-route-1"]').waitFor();
    });

    await step("save again and assert the delta panel shows the 50% reduction", async () => {
      await page.locator('[data-testid="spaghetti-save"]').click();
      await page.waitForFunction(() => document.querySelector('[data-testid="spaghetti-version-badge"]')?.textContent?.includes("v2"));

      await page.locator('[data-testid="spaghetti-route-1-distance"]').waitFor();
      const route1Distance = await page.locator('[data-testid="spaghetti-route-1-distance"]').textContent();
      assert(numeric(route1Distance) === 35, `expected route 1's (proposed) distance to read 35 m/trip, got ${JSON.stringify(route1Distance)}`);

      const deltaPctText = await page.locator('[data-testid="spaghetti-delta-overall-pct"]').textContent();
      assert(numeric(deltaPctText) === -50, `expected the delta panel's overall row to show a 50% reduction, got ${JSON.stringify(deltaPctText)}`);
    });

    await step("playback: start the animation on the traced route and confirm it runs with no page errors", async () => {
      await page.locator('[data-testid="spaghetti-layout-mode-current"]').click();
      await page.locator('[data-testid="spaghetti-playback-route-select"]').selectOption({ label: "Register to grinder" });
      const toggle = page.locator('[data-testid="spaghetti-playback-toggle"]');
      await toggle.click();
      assert(await toggle.getAttribute("data-playing") === "true", "expected the playback toggle to report data-playing=\"true\" after clicking Play");
      await page.waitForTimeout(300); // let a few animation frames run
      await toggle.click(); // pause
      assert(await toggle.getAttribute("data-playing") === "false", "expected the playback toggle to report data-playing=\"false\" after clicking Pause");
    });
  } catch (err) {
    await finish(browser, false, err);
    return;
  }

  await finish(browser, true, null);
}

async function finish(browser, ok, err) {
  await browser.close();

  const failedSteps = steps.filter((s) => s.status === "FAIL");
  const overallOk = ok && failedSteps.length === 0 && pageErrors.length === 0;

  console.log("\n========== SMOKE TEST SUMMARY ==========");
  console.log(`Steps: ${steps.length} run, ${steps.filter((s) => s.status === "PASS").length} passed, ${failedSteps.length} failed`);
  console.log(`Page errors: ${pageErrors.length}`);
  console.log(`Console errors: ${consoleErrors.length}`);
  if (err) console.log(`Thrown error: ${err instanceof Error ? err.message : String(err)}`);
  if (pageErrors.length > 0) {
    console.log("Page error detail:");
    for (const e of pageErrors) console.log(`  - ${e}`);
  }
  console.log(overallOk ? "RESULT: PASS" : "RESULT: FAIL");
  console.log("=========================================");

  process.exit(overallOk ? 0 : 1);
}

main().catch((err) => {
  console.error("Unhandled error in smoke script:", err);
  process.exit(1);
});
