#!/usr/bin/env python3
"""Regenerate engine/sigma_engine/advisor/prompt_pack.py from prompts/.

WHY THIS EXISTS NOW: prompt_pack.py's own docstring says "GENERATED by the
prompt-pack generator -- do not edit by hand; edit prompts/ via the
generator instead," and the generator was not in the repo. So the only way
to add a tool was to hand-edit a 33KB generated file against a test that
compares it to the prompt files byte-for-byte -- exactly the situation the
docstring was warning against. Adding T-35 is what surfaced it.

The module embeds the prompt text as constants so the PyInstaller-packaged
engine can serve GET /advisor/export without reading prompts/ off disk
(sigma_engine.spec ships no data files). tests/test_prompt_pack.py asserts
every constant matches its file, so drift fails CI rather than shipping a
stale prompt.

Usage:
    python3 scripts/generate-prompt-pack.py
"""

from __future__ import annotations

import pathlib
import sys

REPO = pathlib.Path(__file__).resolve().parents[1]
PROMPTS = REPO / "prompts"
TARGET = REPO / "engine" / "sigma_engine" / "advisor" / "prompt_pack.py"

HEADER = '''"""GENERATED by scripts/generate-prompt-pack.py -- do not edit by hand; edit the
files under prompts/ and re-run the generator. The portable prompt files
(prompts/tools/*.md + prompts/tollgates/*.md), embedded as constants so the packaged
engine (PyInstaller, sigma_engine.spec datas=[]) can serve GET /advisor/export
without reading prompts/ off disk -- the same ship-the-text-in-code pattern as
rubric_items.py. tests/test_prompt_pack.py asserts every constant matches its file
byte-for-byte, so drift between this module and prompts/ fails CI."""

from __future__ import annotations

'''


def _tool_id(path: pathlib.Path) -> str:
    """`T-35-gage-rr.md` -> `T-35`. The filename carries the id, and
    test_prompt_pack asserts every registry tool appears exactly once."""
    stem = path.stem
    return "-".join(stem.split("-")[:2])


def main() -> int:
    tool_files = sorted((PROMPTS / "tools").glob("*.md"), key=_tool_id)
    tollgate_files = sorted((PROMPTS / "tollgates").glob("*.md"))
    if not tool_files or not tollgate_files:
        print("prompts/ does not look complete -- refusing to generate", file=sys.stderr)
        return 1

    # The footer is byte-identical across the pack; derive it rather than
    # keeping a second copy that could drift from the files.
    first = tool_files[0].read_text()
    marker = "---\n\n**What this prompt is, honestly.**"
    if marker not in first:
        print(f"{tool_files[0].name} has no fixed footer -- cannot derive it", file=sys.stderr)
        return 1
    footer = first[first.index(marker) :].rstrip("\n")

    lines: list[str] = [HEADER]
    lines.append("# The fixed footer every prompt file ends with (byte-identical across the pack).\n")
    lines.append(f"FIXED_FOOTER = {footer!r}\n\n")

    lines.append("# tool_id -> (filename under prompts/tools/, full file text)\n")
    lines.append("TOOL_PROMPT_FILES: dict[str, tuple[str, str]] = {\n")
    for path in tool_files:
        lines.append(f"    {_tool_id(path)!r}: ({path.name!r}, {path.read_text()!r}),\n")
    lines.append("}\n\n")

    lines.append("# phase -> (filename under prompts/tollgates/, full file text)\n")
    lines.append("TOLLGATE_PROMPT_FILES: dict[str, tuple[str, str]] = {\n")
    for path in tollgate_files:
        lines.append(f"    {path.stem.capitalize()!r}: ({path.name!r}, {path.read_text()!r}),\n")
    lines.append("}\n\n")

    # The two accessors the routes use. Emitted rather than kept in a
    # separate module so the whole pack is one generated file, which is what
    # makes the byte-for-byte test meaningful.
    lines.append(
        'def tool_prompt_text(tool_id: str) -> str | None:\n'
        '    """The portable prompt for one tool, or None for an unknown tool_id."""\n'
        "    entry = TOOL_PROMPT_FILES.get(tool_id)\n"
        "    return entry[1] if entry else None\n\n\n"
        'def tollgate_prompt_text(phase: str) -> str | None:\n'
        '    """The portable Champion prompt for one tollgate phase, or None."""\n'
        "    entry = TOLLGATE_PROMPT_FILES.get(phase)\n"
        "    return entry[1] if entry else None\n"
    )

    TARGET.write_text("".join(lines))
    print(f"wrote {TARGET.relative_to(REPO)} -- {len(tool_files)} tools, {len(tollgate_files)} tollgates")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
